name: example-environment
channels:
  - conda-forge
dependencies:
matplotlib==3.5.3
numpy==1.22.4
packaging==21.3
pandas==1.5.1
pillow==9.3.0
pyparsing==3.0.9
python-dateutil==2.8.2
pytz==2022.6
scipy==1.9.1
seaborn==0.10.1
six==1.16.0
opencv-python-headless==4.7.0.72
shapely==1.8.4
